### PR TITLE
release v0.13.1

### PR DESCRIPTION
**Pull request by anthony-maurandi**
Purpose
Release a new version of ficum compatible with java17.

Solution
Version bumped in parent and children pom files.

cf. unreleased SNAPSHOT version: https://github.com/bitgrip/ficum/commit/51fedf8569c518cefe432d1bb4c5535258afa18a

### CODE REVIEW

**Comment by anthony-maurandi** [comment]
Hello @hschott, @fotopixel, @anupamck , @nilasson , @mmueller90  and @karolkarolkarolkarol
Could someone please review this PR and take care of the release?
I seem to be missing all the permissions required to apply the steps in https://github.com/bitgrip/ficum/pull/32#issuecomment-1660746983

**Comment by anthony-maurandi** [comment]
Hello @anupamck ,
Any news regarding this PR to release of a new version?

**Comment by anupamck** [comment]
@anthony-maurandi - merged!

**Comment by anthony-maurandi** [comment]
Hello @anupamck ,
Massive thanks  :+1:
What is the next step to get version 0.13.1 published in maven?
image

**Comment by anthony-maurandi** [comment]
Hello @fotopixel and @hschott,
Regarding your comments 
- https://github.com/bitgrip/ficum/pull/32#issuecomment-1660652180
- https://github.com/bitgrip/ficum/pull/32#issuecomment-1660746983
Who has the permissions in https://oss.sonatype.org/ to stage the artifacts through the validation process?

**Pull request merged**
